chu_gestion_utilisateur_page_login:
    path:     /
    defaults: { _controller: CHUgestionUtilisateurBundle:gestionUtilisateur:index }

chu_gestion_utilisateur_page_perso:
    path:     /PagePerso
    defaults: { _controller: CHUgestionUtilisateurBundle:gestionUtilisateur:login }

chu_gestion_utilisateur_page_creation:
    path:     /CreationUtilisateur
    defaults: { _controller: CHUgestionUtilisateurBundle:gestionUtilisateur:pageCreationUtilisateur }

chu_gestion_utilisateur_creation:
    path:     /Creation
    defaults: { _controller: CHUgestionUtilisateurBundle:gestionUtilisateur:creationUtilisateur }

chu_gestion_utilisateur_deconnection:
    path:     /Deconnection
    defaults: { _controller: CHUgestionUtilisateurBundle:gestionUtilisateur:deconnection }
