chu_administartion_homepage:
    path:     /
    defaults: { _controller: CHUAdministartionBundle:Default:index }


creer_compte:
    path:     /creer_compte
    defaults: { _controller: CHUAdministartionBundle:Default:creerCompte }


    

afficher_etudes:
    path:     /afficher_etudes
    defaults: { _controller: CHUAdministartionBundle:Default:afficherEtudes }
    
afficher_users_admin:
    path:     /afficher_medecins
    defaults: { _controller: CHUAdministartionBundle:Default:afficherMedecins }
    
supprimer_user:
     path:     /supprimer_user
     defaults: { _controller: CHUAdministartionBundle:Default:supprimerUser }


    