<?php

namespace CHU\EtudeBundle\Repository;

/**
 * Type_Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_Repository extends \Doctrine\ORM\EntityRepository
{
}
