<?php

namespace CHU\gestionUtilisateurBundle\Repository;

/**
 * soignantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class soignantRepository extends \Doctrine\ORM\EntityRepository
{
}
