#CURRENT VERSION

chu__homepage:
    path:     /
    defaults: { _controller: CHUEtudeBundle:Default:index}

chu_etude_build_form:
    path:     /create
    defaults: { _controller: CHUEtudeBundle:Default:createFormBuilder }

chu_etude_submit_builded_form:
    path:     /submit
    defaults: { _controller: CHUEtudeBundle:Default:submitBuiltForm }

chu_etude_show_etudes:
    path:     /list
    defaults: { _controller: CHUEtudeBundle:Default:showListForms }

chu_etude_action_questionnaire:
    path:     /show
    defaults: { _controller: CHUEtudeBundle:Default:handleChoice}

chu_etude_questionnaire_repondu:
    path:     /answers/submit
    defaults: { _controller: CHUEtudeBundle:Default:submitFormAnswered}
