#CURRENT VERSION

chu_homepage:
    path:     /
    defaults: { _controller: CHUEtudeBundle:Default:index}

chu_etude_create_form:
    path:     /create
    defaults: { _controller: CHUEtudeBundle:Default:create_form }

chu_etude_build_form:
    path:     /build
    defaults: { _controller: CHUEtudeBundle:Default:build_form }

chu_etude_submit_builded_form:
    path:     /submit
    defaults: { _controller: CHUEtudeBundle:Default:submitBuiltForm }

chu_etude_show_etudes:
    path:     /list
    defaults: { _controller: CHUEtudeBundle:Default:showListForms }

chu_etude_questionnaire_repondu:
    path:     /answers/submit
    defaults: { _controller: CHUEtudeBundle:Default:submitFormAnswered}

chu_etude_delete_form:
    path:     /delete
    defaults: { _controller: CHUEtudeBundle:Default:deleteForm}

chu_etude_answer_form:
    path:     /answers
    defaults: { _controller: CHUEtudeBundle:Default:answerForm}

chu_etude_check_results_form:
    path:     /results
    defaults: { _controller: CHUEtudeBundle:Default:checkResults}
